# Generated by Django 4.2.7 on 2023-11-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GS_Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamename',
            new_name='name',
        ),
    ]
