# Generated by Django 4.2.7 on 2023-11-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GS_Backend', '0002_rename_gamename_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GS_Backend.game'),
        ),
    ]
