# Generated by Django 4.2.7 on 2023-11-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS_Backend', '0003_leaderboardentry_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='gameurl',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='long_des',
            field=models.CharField(default=None, max_length=1200),
        ),
        migrations.AddField(
            model_name='game',
            name='shrt_des',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
