# Generated by Django 4.2.7 on 2023-11-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GS_Backend', '0004_game_developer_game_gameurl_game_genre_game_long_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameurl',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='long_des',
            field=models.CharField(default='None', max_length=1200),
        ),
        migrations.AlterField(
            model_name='game',
            name='shrt_des',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
