# Generated by Django 4.2.7 on 2023-11-17 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GS_Backend', '0005_alter_game_developer_alter_game_gameurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameurl',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='long_des',
            field=models.CharField(default=None, max_length=1200),
        ),
        migrations.AlterField(
            model_name='game',
            name='shrt_des',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='GS_Backend.game'),
        ),
        migrations.CreateModel(
            name='GameTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=25)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devtags', to='GS_Backend.game')),
            ],
        ),
    ]
